### ISSUE TITLE
Can you make it  Swift 3 and Xcode 8 compatible?

### ISSUE THREAD

**Issue by anandramv** [elaniin/AccountKit-iOS-Swift#3]
Hi there!

It is a great example to learn about Facebook kit. Thank you very much for that.

However, I am getting error when I am running the project in the Xcode 8. Can you make it swift 3 and Xcode 8 compatible?

Thank you!

**Comment by adriangomezme** [comment]
Hi @anandramv , I will work in the swift 3 and Xcode 8 version tonight.

**Comment by anandramv** [comment]
Hi @elaniin , thank you very much!! 
Can you also help me understand how to persist the session when app closes? 
I am having trouble in understanding how to maintain the session in the app with the token which is valid for 60 days.

**Comment by adriangomezme** [comment]
hey @anandramv , now is compatible with swift 3.0
